spring:
  application:
    name: practice-multi-module
  profiles:
    active: local
  config:
    activate:
      on-profile: local
    import:
      - logging.yml

---
spring:
  config:
    activate:
      on-profile: local-dev
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: staging
---
spring:
  config:
    activate:
      on-profile: live